=== Inconcessus/html5-tibia-engine/data/1098/npcs/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Monster",
  "description": "Schema for a Monster",
  "type": "object",
  "properties": {
    "trade": {
      "description": "The trade items of the NPC",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the trade thing",
            "type": "string"
          },
          "price": {
            "description": "The price of the trade thing",
            "type": "integer",
            "minimum": 0
          },
          "id": {
            "description": "The identifier of the trade thing",
            "type": "integer",
            "minimum": 0
          },
          "type": {
            "description": "The type of the trade thing (buy/sell)",
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "price",
          "id",
          "type"
        ]
      }
    },
    "hearingRange": {
      "description": "The hearing range of the NPC",
      "type": "integer",
      "minimum": 0
    },
    "wanderRange": {
      "description": "The wandering range of the NPC",
      "type": "integer",
      "minimum": 0
    },
    "sayings": {
      "description": "Sayings of the NPC",
      "type": "object",
      "properties": {
        "texts": {
          "description": "Array of random sayings of the NPC",
          "type": "array",
          "minItems": 1
        },
        "slowness": {
          "description": "Slowness of sayings of the NPC",
          "type": "integer",
          "minimum": 0
        },
        "chance": {
          "description": "Chance of sayings of the NPC",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      },
      "additionalProperties": false,
      "required": [
        "texts",
        "slowness",
        "chance"
      ]
    },
    "greetings": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    },
    "farewells": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    },
    "creatureStatistics": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "health": {
          "type": "integer",
          "minimum": 0
        },
        "maxHealth": {
          "type": "integer",
          "minimum": 0
        },
        "mana": {
          "type": "integer",
          "minimum": 0
        },
        "maxMana": {
          "type": "integer",
          "minimum": 0
        },
        "attack": {
          "type": "integer",
          "minimum": 0
        },
        "attackSlowness": {
          "type": "integer",
          "minimum": 0
        },
        "defense": {
          "type": "integer",
          "minimum": 0
        },
        "slowness": {
          "type": "integer",
          "minimum": 0
        },
        "outfit": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "minimum": 0
            },
            "details": {
              "type": "object",
              "properties": {
                "head": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                },
                "body": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                },
                "legs": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                },
                "feet": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                }
              },
              "additionalProperties": false,
              "required": [
                "head",
                "body",
                "legs",
                "feet"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "id"
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "health",
        "maxHealth",
        "mana",
        "maxMana",
        "attack",
        "attackSlowness",
        "defense",
        "slowness",
        "outfit"
      ]
    },
    "script": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "hearingRange",
    "wanderRange"
  ]
}

=== Inconcessus/html5-tibia-engine/data/1098/npcs/definitions/humphrey.json
{
  "creatureStatistics": {
    "name": "Humphrey",
    "health": 50,
    "maxHealth": 50,
    "attack": 1,
    "mana": 0,
    "maxMana": 0,
    "attackSlowness": 40,
    "defense": 5,
    "slowness": 40,
    "outfit": {
      "id": 57
    }
  },
  "hearingRange": 5,
  "wanderRange": 2,
  "farewells": [
    "bye"
  ],
  "greetings": [
    "hello",
    "hi"
  ],
  "sayings": {
    "texts": [
      "..."
    ],
    "slowness": 300,
    "chance": 0.75
  },
  "script": "humphrey.js"
}

=== Inconcessus/html5-tibia-engine/data/1098/npcs/definitions/jack.json
{
  "creatureStatistics": {
    "name": "Jack",
    "health": 50,
    "maxHealth": 50,
    "attack": 1,
    "mana": 0,
    "maxMana": 0,
    "attackSlowness": 40,
    "defense": 5,
    "slowness": 40,
    "outfit": {
      "id": 129,
      "details": {
        "head": 97,
        "body": 95,
        "legs": 116,
        "feet": 114
      }
    }
  },
  "hearingRange": 5,
  "wanderRange": 2,
  "farewells": [
    "bye"
  ],
  "greetings": [
    "hello",
    "hi"
  ],
  "sayings": {
    "texts": [
      "Yoho-Yoho, a law abiding sailors life for me!"
    ],
    "slowness": 300,
    "chance": 0.75
  },
  "script": "jack.js"
}

=== Inconcessus/html5-tibia-engine/data/1098/npcs/definitions/teller.json
{
  "creatureStatistics": {
    "name": "Teller",
    "health": 50,
    "maxHealth": 50,
    "attack": 1,
    "mana": 0,
    "maxMana": 0,
    "attackSlowness": 40,
    "defense": 5,
    "slowness": 20,
    "outfit": {
      "id": 141,
      "details": {
        "head": 12,
        "body": 2,
        "legs": 12,
        "feet": 10
      }
    }
  },
  "hearingRange": 5,
  "wanderRange": 2,
  "farewells": [
    "bye"
  ],
  "greetings": [
    "hello",
    "hi"
  ],
  "sayings": {
    "texts": [
      "A safe place to store your items!"
    ],
    "slowness": 300,
    "chance": 0.75
  },
  "script": "teller.js"
}

=== Inconcessus/html5-tibia-engine/data/1098/npcs/definitions/sarah.json
{
  "creatureStatistics": {
    "name": "Sarah",
    "health": 50,
    "maxHealth": 50,
    "attack": 1,
    "mana": 0,
    "maxMana": 0,
    "attackSlowness": 40,
    "defense": 5,
    "slowness": 20,
    "outfit": {
      "id": 140,
      "details": {
        "head": 39,
        "body": 105,
        "legs": 96,
        "feet": 59
      }
    }
  },
  "hearingRange": 5,
  "wanderRange": 2,
  "farewells": [
    "bye"
  ],
  "greetings": [
    "hello",
    "hi"
  ],
  "sayings": {
    "texts": [
      "♫♪♪",
      "♪♫♪♫",
      "What a cloudy day.."
    ],
    "slowness": 300,
    "chance": 0.75
  },
  "script": "sarah.js"
}

=== Inconcessus/html5-tibia-engine/data/1098/npcs/definitions/ghost.json
{
  "creatureStatistics": {
    "name": "A Strange Ghost",
    "health": 50,
    "maxHealth": 50,
    "mana": 0,
    "maxMana": 0,
    "attack": 1,
    "attackSlowness": 40,
    "defense": 5,
    "slowness": 100,
    "outfit": {
      "id": 48
    }
  },
  "hearingRange": 5,
  "wanderRange": 2,
  "farewells": [
    "bye"
  ],
  "greetings": [
    "hello",
    "hi"
  ],
  "sayings": {
    "texts": [
      "..."
    ],
    "slowness": 300,
    "chance": 0.75
  }
}
