=== Inconcessus/html5-tibia-engine/data/740/monsters/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Monster",
  "description": "Schema for a Monster",
  "type": "object",
  "properties": {
    "experience": {
      "description": "The experience points of the monster",
      "type": "integer",
      "minimum": 0
    },
    "loot": {
      "description": "The loot of the monster",
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "The identifier of the loot thing",
            "type": "integer",
            "minimum": 0
          },
          "probability": {
            "description": "The probability of dropping the loot thing",
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          "min": {
            "description": "The minimum number of the loot thing",
            "type": "integer",
            "minimum": 1
          },
          "max": {
            "description": "The maximum number of the loot thing",
            "type": "integer",
            "minimum": 1
          }
        },
        "additionalProperties": false,
        "required": [
          "id",
          "probability"
        ]
      }
    },
    "fluidType": {
      "description": "The fluid type of the monster",
      "type": "integer",
      "minimum": 0,
      "maximum": 2
    },
    "corpse": {
      "description": "The corpse identifier of the monster",
      "type": "integer",
      "minimum": 0
    },
    "sayings": {
      "description": "Sayings of the monster",
      "type": "object",
      "properties": {
        "texts": {
          "description": "Array of random sayings of the monster",
          "type": "array",
          "minItems": 1
        },
        "slowness": {
          "description": "Slowness of sayings of the monster",
          "type": "integer",
          "minimum": 0
        },
        "chance": {
          "description": "Chance of sayings of the monster",
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      },
      "additionalProperties": false,
      "required": [
        "texts",
        "slowness"
      ]
    },
    "spells": {
      "type": "array",
      "minItems": 1
    },
    "behaviour": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "fleeHealth": {
          "type": "integer",
          "minimum": 0
        },
        "openDoors": {
          "type": "boolean"
        },
        "senseInvisible": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "required": [
        "type",
        "fleeHealth",
        "openDoors",
        "senseInvisible"
      ]
    },
    "creatureStatistics": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "health": {
          "type": "integer",
          "minimum": 0
        },
        "maxHealth": {
          "type": "integer",
          "minimum": 0
        },
        "mana": {
          "type": "integer",
          "minimum": 0
        },
        "maxMana": {
          "type": "integer",
          "minimum": 0
        },
        "attack": {
          "type": "integer",
          "minimum": 0
        },
        "attackSlowness": {
          "type": "integer",
          "minimum": 0
        },
        "defense": {
          "type": "integer",
          "minimum": 0
        },
        "speed": {
          "type": "integer",
          "minimum": 0
        },
        "outfit": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "minimum": 0
            },
            "details": {
              "type": "object",
              "properties": {
                "head": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                },
                "body": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                },
                "legs": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                },
                "feet": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 133
                }
              },
              "additionalProperties": false,
              "required": [
                "head",
                "body",
                "legs",
                "feet"
              ]
            }
          },
          "additionalProperties": false,
          "required": [
            "id"
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "health",
        "maxHealth",
        "mana",
        "maxMana",
        "attack",
        "attackSlowness",
        "defense",
        "speed",
        "outfit"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "experience",
    "corpse",
    "behaviour",
    "fluidType"
  ]
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/spider.json
{
  "creatureStatistics": {
    "name": "Spider",
    "health": 30,
    "maxHealth": 30,
    "mana": 0,
    "maxMana": 0,
    "attack": 10,
    "attackSlowness": 40,
    "defense": 5,
    "speed": 30,
    "outfit": {
      "id": 30
    }
  },
  "fluidType": 1,
  "experience": 0,
  "corpse": 2807,
  "behaviour": {
    "type": "HOSTILE",
    "fleeHealth": 10,
    "openDoors": false,
    "senseInvisible": false
  }
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/rabbit.json
{
  "creatureStatistics": {
    "name": "Rabbit",
    "health": 50,
    "maxHealth": 50,
    "mana": 0,
    "maxMana": 0,
    "attack": 0,
    "attackSlowness": 40,
    "defense": 5,
    "speed": 100,
    "outfit": {
      "id": 74
    }
  },
  "fluidType": 0,
  "experience": 0,
  "behaviour": {
    "type": "FRIENDLY",
    "fleeHealth": 50,
    "openDoors": true,
    "senseInvisible": false
  },
  "corpse": 3119,
  "loot": [
    {"id": 2666, "probability": 1, "min": 1, "max": 3}
  ],
  "sayings": {
   "texts": ["Mip mip mip"],
   "slowness": 300,
   "chance": 0.75
  }
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/rat.json
{
  "creatureStatistics": {
    "name": "Rat",
    "health": 20,
    "mana": 0,
    "maxMana": 0,
    "maxHealth": 20,
    "attack": 1,
    "attackSlowness": 40,
    "defense": 5,
    "speed": 30,
    "outfit": {
      "id": 21
    }
  },
  "fluidType": 0,
  "experience": 50,
  "corpse": 2813,
  "behaviour": {
    "type": "HOSTILE",
    "fleeHealth": 5,
    "openDoors": true,
    "senseInvisible": false
  },
  "loot": [
    {
      "id": 2148,
      "probability": 1,
      "min": 1,
      "max": 4
    },
    {
      "id": 2696,
      "probability": 0.1,
      "min": 1,
      "max": 1
    }
  ],
  "sayings": {
    "texts": [
      "Meep!"
    ],
    "slowness": 300,
    "chance": 0.75
  }
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/black-sheep.json
{
  "creatureStatistics": {
    "name": "Sheep",
    "health": 5,
    "maxHealth": 5,
    "mana": 0,
    "maxMana": 0,
    "attack": 0,
    "attackSlowness": 40,
    "defense": 5,
    "speed": 30,
    "outfit": {
      "id": 13
    }
  },
  "fluidType": 0,
  "experience": 0,
  "corpse": 2914,
  "behaviour": {
    "type": "FRIENDLY",
    "fleeHealth": 4,
    "openDoors": false,
    "senseInvisible": false
  },
  "loot": [
    {"id": 2666, "probability": 1, "min": 1, "max": 3}
  ],
  "sayings": {
   "texts": ["Behhh"],
   "slowness": 300,
   "chance": 0.75
  }
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/cave-rat.json
{
  "creatureStatistics": {
    "name": "Cave Rat",
    "health": 30,
    "maxHealth": 30,
    "mana": 0,
    "maxMana": 0,
    "attack": 8,
    "attackSlowness": 40,
    "defense": 5,
    "speed": 30,
    "outfit": {
      "id": 56
    }
  },
  "fluidType": 0,
  "experience": 10,
  "behaviour": {
    "type": "HOSTILE",
    "fleeHealth": 0,
    "openDoors": true,
    "senseInvisible": false
  },
  "corpse": 2813,
  "loot": [
    {
      "id": 2148,
      "probability": 1,
      "min": 1,
      "max": 4
    },
    {
      "id": 2696,
      "probability": 0.1,
      "min": 1,
      "max": 1
    }
  ],
  "sayings": {
    "texts": [
      "Meep!",
      "Meeeeep!"
    ],
    "slowness": 300,
    "chance": 0.75
  }
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/bear.json
{
  "creatureStatistics": {
    "name": "Bear",
    "health": 80,
    "maxHealth": 80,
    "mana": 0,
    "maxMana": 0,
    "attack": 50,
    "attackSlowness": 40,
    "defense": 5,
    "speed": 30,
    "outfit": {
      "id": 16
    }
  },
  "fluidType": 0,
  "experience": 0,
  "corpse": 2849,
  "behaviour": {
    "type": "HOSTILE",
    "fleeHealth": 60,
    "openDoors": false,
    "senseInvisible": false
  },
  "loot": [
    {"id": 2666, "probability": 1, "min": 1, "max": 3}
  ],
  "sayings": {
   "texts": ["Grrrr", "Groar"],
   "slowness": 300,
   "chance": 0.75
  }
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/skeleton.json
{
  "creatureStatistics": {
    "name": "Skeleton",
    "health": 50,
    "maxHealth": 50,
    "attack": 10,
    "mana": 0,
    "maxMana": 0,
    "attackSlowness": 40,
    "defense": 10,
    "speed": 50,
    "outfit": {
      "id": 33
    }
  },
  "fluidType": 2,
  "experience": 35,
  "corpse": 2843,
  "behaviour": {
    "type": "HOSTILE",
    "fleeHealth": 0,
    "openDoors": true,
    "senseInvisible": false
  },
  "loot": [
    {
      "id": 2229,
      "probability": 1,
      "min": 1,
      "max": 1
    },
    {
      "id": 2230,
      "probability": 1
    },
    {
      "id": 2231,
      "probability": 1
    },
    {
      "id": 2148,
      "probability": 1,
      "min": 1,
      "max": 7
    },
    {
      "id": 2473,
      "probability": 0.5
    }
  ],
  "spells": [{
    "id": 6,
    "chance": 1,
    "cooldown": 50
  }],
  "sayings": {
    "texts": [
      "Rattle!"
    ],
    "slowness": 300,
    "chance": 0.75
  }
}

=== Inconcessus/html5-tibia-engine/data/740/monsters/definitions/slime.json
{
  "creatureStatistics": {
    "name": "Slime",
    "health": 150,
    "maxHealth": 150,
    "mana": 0,
    "maxMana": 0,
    "attack": 0,
    "attackSlowness": 40,
    "defense": 5,
    "speed": 60,
    "outfit": {
      "id": 19
    }
  },
  "fluidType": 1,
  "experience": 160,
  "corpse": 1496,
  "behaviour": {
    "type": "HOSTILE",
    "fleeHealth": 0,
    "openDoors": false,
    "senseInvisible": false
  },
  "loot": [],
  "sayings": {
   "texts": ["Blubb"],
   "slowness": 300,
   "chance": 0.75
  }
}
